### ISSUE TITLE
Need to Improve code readability by add comments and refactor the code structure

### ISSUE THREAD

**Issue by azaryasph** [azaryasph/minpro-predict-customer-personality#1]
In the EDA section of categorical feature distribution, add some comments to improve the code readability, and restructure the code to make the code easier to maintain.
This should be done ASAP ‼️

**Comment by stefansphtr** [comment]
Hi!, I would like to work on this project

**Comment by azaryasph** [comment]
You're assigned🎉. Make sure to make the improvement ASAP, Thank you!

**Comment by stefansphtr** [comment]
> You're assigned🎉. Make sure to make the improvement ASAP, Thank you!

Sure I'll do it!

**Comment by azaryasph** [comment]
Wow, the pull request really shines! ✨ The refactoring in EDA section has significantly boosted performance  and the clean code principle like DRY and KISS is incredibly well-implemented. Thanks for your contribution!
